//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PercentCalculator.Resources.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PercentCalculator.Resources.Language.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount:.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        internal static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        internal static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        internal static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Change.
        /// </summary>
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compound frequency Per Year:.
        /// </summary>
        internal static string CompoundFrequency {
            get {
                return ResourceManager.GetString("CompoundFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPOUND INTEREST.
        /// </summary>
        internal static string CompoundInterest {
            get {
                return ResourceManager.GetString("CompoundInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compound Interest.
        /// </summary>
        internal static string CompoundInterest1 {
            get {
                return ResourceManager.GetString("CompoundInterest1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculates Compound Interest.
        /// </summary>
        internal static string compoundInterest2 {
            get {
                return ResourceManager.GetString("compoundInterest2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost:.
        /// </summary>
        internal static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculates Cumulative Growth.
        /// </summary>
        internal static string cumulative {
            get {
                return ResourceManager.GetString("cumulative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUMULATIVE GROWTH CALCULATOR.
        /// </summary>
        internal static string CumulativeGrowthCalculator {
            get {
                return ResourceManager.GetString("CumulativeGrowthCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cumulative Growth Calculator.
        /// </summary>
        internal static string CumulativeGrowthCalculator1 {
            get {
                return ResourceManager.GetString("CumulativeGrowthCalculator1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference:.
        /// </summary>
        internal static string Difference {
            get {
                return ResourceManager.GetString("Difference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to discount.
        /// </summary>
        internal static string Discoun {
            get {
                return ResourceManager.GetString("Discoun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculates Amount Doubling Time.
        /// </summary>
        internal static string doubling {
            get {
                return ResourceManager.GetString("doubling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOUBLING CALCULATOR.
        /// </summary>
        internal static string DoublingCalculator {
            get {
                return ResourceManager.GetString("DoublingCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doubling Calculator.
        /// </summary>
        internal static string DoublingCalculator1 {
            get {
                return ResourceManager.GetString("DoublingCalculator1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doubling t:.
        /// </summary>
        internal static string Doublingt {
            get {
                return ResourceManager.GetString("Doublingt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End year:.
        /// </summary>
        internal static string EndYear {
            get {
                return ResourceManager.GetString("EndYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter 1st Value:.
        /// </summary>
        internal static string EnterFirstValue {
            get {
                return ResourceManager.GetString("EnterFirstValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter 2nd Value:.
        /// </summary>
        internal static string EnterSecondValue {
            get {
                return ResourceManager.GetString("EnterSecondValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final balance:.
        /// </summary>
        internal static string FinalBalance {
            get {
                return ResourceManager.GetString("FinalBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final value:.
        /// </summary>
        internal static string FinalValue {
            get {
                return ResourceManager.GetString("FinalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate percentage from fraction..
        /// </summary>
        internal static string fractionPercentage {
            get {
                return ResourceManager.GetString("fractionPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRACTION TO PERCENTAGE.
        /// </summary>
        internal static string FractionToPercentage {
            get {
                return ResourceManager.GetString("FractionToPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fraction to Percentage.
        /// </summary>
        internal static string FractionToPercentage1 {
            get {
                return ResourceManager.GetString("FractionToPercentage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Value:.
        /// </summary>
        internal static string FromValue {
            get {
                return ResourceManager.GetString("FromValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Cost:.
        /// </summary>
        internal static string GrossCost {
            get {
                return ResourceManager.GetString("GrossCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Price:.
        /// </summary>
        internal static string GrossPrice {
            get {
                return ResourceManager.GetString("GrossPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growth Rate.
        /// </summary>
        internal static string GrowthRate {
            get {
                return ResourceManager.GetString("GrowthRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase.
        /// </summary>
        internal static string Increas {
            get {
                return ResourceManager.GetString("Increas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase:.
        /// </summary>
        internal static string Increase {
            get {
                return ResourceManager.GetString("Increase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase By.
        /// </summary>
        internal static string IncreaseBy {
            get {
                return ResourceManager.GetString("IncreaseBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inflation:.
        /// </summary>
        internal static string Inflation {
            get {
                return ResourceManager.GetString("Inflation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculates Inflation By Time.
        /// </summary>
        internal static string inflation1 {
            get {
                return ResourceManager.GetString("inflation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFLATION CALCULATOR.
        /// </summary>
        internal static string InflationCalculator {
            get {
                return ResourceManager.GetString("InflationCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inflation Calculator.
        /// </summary>
        internal static string InflationCalculator1 {
            get {
                return ResourceManager.GetString("InflationCalculator1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial balance:.
        /// </summary>
        internal static string InitialBalance {
            get {
                return ResourceManager.GetString("InitialBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial value:.
        /// </summary>
        internal static string InitialValue {
            get {
                return ResourceManager.GetString("InitialValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest rate:.
        /// </summary>
        internal static string InterestRate {
            get {
                return ResourceManager.GetString("InterestRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is same as.
        /// </summary>
        internal static string IsSameAs {
            get {
                return ResourceManager.GetString("IsSameAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is what percent of.
        /// </summary>
        internal static string IsWhatPercentOf {
            get {
                return ResourceManager.GetString("IsWhatPercentOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculates Loan Over Time.
        /// </summary>
        internal static string loan1 {
            get {
                return ResourceManager.GetString("loan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOAN CALCULATOR.
        /// </summary>
        internal static string LoanCalculator {
            get {
                return ResourceManager.GetString("LoanCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Calculator.
        /// </summary>
        internal static string LoanCalculator1 {
            get {
                return ResourceManager.GetString("LoanCalculator1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin:.
        /// </summary>
        internal static string Margin {
            get {
                return ResourceManager.GetString("Margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARGIN CALCULATOR.
        /// </summary>
        internal static string MarginCalculator {
            get {
                return ResourceManager.GetString("MarginCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin Calculator.
        /// </summary>
        internal static string MarginCalculator1 {
            get {
                return ResourceManager.GetString("MarginCalculator1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARGIN AND SALES TAX CALCULATOR.
        /// </summary>
        internal static string MarginSalesTax {
            get {
                return ResourceManager.GetString("MarginSalesTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin and Sales Tax Calculator.
        /// </summary>
        internal static string MarginSalesTax2 {
            get {
                return ResourceManager.GetString("MarginSalesTax2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARGIN AND VAT CALCULATOR.
        /// </summary>
        internal static string MarginVat {
            get {
                return ResourceManager.GetString("MarginVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin and Vat Calculator.
        /// </summary>
        internal static string MarginVat2 {
            get {
                return ResourceManager.GetString("MarginVat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markup:.
        /// </summary>
        internal static string Markup {
            get {
                return ResourceManager.GetString("Markup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARKUP CALCULATOR.
        /// </summary>
        internal static string MarkupCalculator {
            get {
                return ResourceManager.GetString("MarkupCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markup Calculator.
        /// </summary>
        internal static string MarkupCalculator1 {
            get {
                return ResourceManager.GetString("MarkupCalculator1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculates selling price based on margin.
        /// </summary>
        internal static string MgDescription {
            get {
                return ResourceManager.GetString("MgDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculates revenue based on markup.
        /// </summary>
        internal static string MkDescription {
            get {
                return ResourceManager.GetString("MkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator Margin and Sales Tax.
        /// </summary>
        internal static string MsDescription {
            get {
                return ResourceManager.GetString("MsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculates Margin and Vat.
        /// </summary>
        internal static string MvDescription {
            get {
                return ResourceManager.GetString("MvDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Price:.
        /// </summary>
        internal static string NetPrice {
            get {
                return ResourceManager.GetString("NetPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of People:.
        /// </summary>
        internal static string NoOfPeople {
            get {
                return ResourceManager.GetString("NoOfPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Periods:.
        /// </summary>
        internal static string NumberOfPeriods {
            get {
                return ResourceManager.GetString("NumberOfPeriods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of years:.
        /// </summary>
        internal static string NumberOfYears {
            get {
                return ResourceManager.GetString("NumberOfYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Of.
        /// </summary>
        internal static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string off {
            get {
                return ResourceManager.GetString("off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price hike from.
        /// </summary>
        internal static string PchDescription1 {
            get {
                return ResourceManager.GetString("PchDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string PchDescription2 {
            get {
                return ResourceManager.GetString("PchDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERCENTAGE CALCULATOR.
        /// </summary>
        internal static string PercentageCalculator {
            get {
                return ResourceManager.GetString("PercentageCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage Calculator.
        /// </summary>
        internal static string PercentageCalculator1 {
            get {
                return ResourceManager.GetString("PercentageCalculator1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERCENTAGE CHANGE.
        /// </summary>
        internal static string PercentageChange {
            get {
                return ResourceManager.GetString("PercentageChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage Change.
        /// </summary>
        internal static string PercentageChange1 {
            get {
                return ResourceManager.GetString("PercentageChange1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERCENTAGE DISCOUNT.
        /// </summary>
        internal static string PercentageDiscount {
            get {
                return ResourceManager.GetString("PercentageDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage Discount.
        /// </summary>
        internal static string PercentageDiscount1 {
            get {
                return ResourceManager.GetString("PercentageDiscount1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERCENTAGE INCREASE.
        /// </summary>
        internal static string PercentageIncrease {
            get {
                return ResourceManager.GetString("PercentageIncrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage Increase.
        /// </summary>
        internal static string PercentageIncrease1 {
            get {
                return ResourceManager.GetString("PercentageIncrease1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERCENTAGE OF.
        /// </summary>
        internal static string PercentageOf {
            get {
                return ResourceManager.GetString("PercentageOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage Of.
        /// </summary>
        internal static string PercentageOf1 {
            get {
                return ResourceManager.GetString("PercentageOf1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent Calculator.
        /// </summary>
        internal static string PercentCalculator {
            get {
                return ResourceManager.GetString("PercentCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is what percent of.
        /// </summary>
        internal static string PoDescription1 {
            get {
                return ResourceManager.GetString("PoDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit:.
        /// </summary>
        internal static string Profit {
            get {
                return ResourceManager.GetString("Profit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result:.
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue:.
        /// </summary>
        internal static string Revenue {
            get {
                return ResourceManager.GetString("Revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALES TAX.
        /// </summary>
        internal static string SalesTax {
            get {
                return ResourceManager.GetString("SalesTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Tax.
        /// </summary>
        internal static string SalesTax1 {
            get {
                return ResourceManager.GetString("SalesTax1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Tax:.
        /// </summary>
        internal static string SalesTaxPercentage {
            get {
                return ResourceManager.GetString("SalesTaxPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selling:.
        /// </summary>
        internal static string Selling {
            get {
                return ResourceManager.GetString("Selling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start year:.
        /// </summary>
        internal static string StartYear {
            get {
                return ResourceManager.GetString("StartYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculates sales tax from Tax %.
        /// </summary>
        internal static string StDescription {
            get {
                return ResourceManager.GetString("StDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Amount:.
        /// </summary>
        internal static string TaxAmount {
            get {
                return ResourceManager.GetString("TaxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate that distributes restaurant bill evenly.
        /// </summary>
        internal static string TcDescription {
            get {
                return ResourceManager.GetString("TcDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip Amount:.
        /// </summary>
        internal static string TipAmount {
            get {
                return ResourceManager.GetString("TipAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIP CALCULATOR.
        /// </summary>
        internal static string TipCalculator {
            get {
                return ResourceManager.GetString("TipCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip Calculator.
        /// </summary>
        internal static string TipCalculator1 {
            get {
                return ResourceManager.GetString("TipCalculator1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip Percentage:.
        /// </summary>
        internal static string TipPercentage {
            get {
                return ResourceManager.GetString("TipPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount:.
        /// </summary>
        internal static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Growth:.
        /// </summary>
        internal static string TotalGrowth {
            get {
                return ResourceManager.GetString("TotalGrowth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total inflation:.
        /// </summary>
        internal static string TotalInflation {
            get {
                return ResourceManager.GetString("TotalInflation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Per Person:.
        /// </summary>
        internal static string TotalPerPerson {
            get {
                return ResourceManager.GetString("TotalPerPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total To Pay:.
        /// </summary>
        internal static string TotalToPay {
            get {
                return ResourceManager.GetString("TotalToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Value:.
        /// </summary>
        internal static string ToValue {
            get {
                return ResourceManager.GetString("ToValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT:.
        /// </summary>
        internal static string Vat {
            get {
                return ResourceManager.GetString("Vat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculates VAT.
        /// </summary>
        internal static string vat1 {
            get {
                return ResourceManager.GetString("vat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT CALCULATOR.
        /// </summary>
        internal static string VatCalculator {
            get {
                return ResourceManager.GetString("VatCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vat Calculator.
        /// </summary>
        internal static string VatCalculator1 {
            get {
                return ResourceManager.GetString("VatCalculator1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is.
        /// </summary>
        internal static string Whatis {
            get {
                return ResourceManager.GetString("Whatis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with.
        /// </summary>
        internal static string With {
            get {
                return ResourceManager.GetString("With", resourceCulture);
            }
        }
    }
}
